from .auth import (
    UniqueViolationError,
    create_user,
    get_user_by_email,
    get_user_by_id,
    upsert_refresh_token,
    get_refresh_token,
    insert_auth_event,
    revoke_refresh_token,
    touch_refresh_token_as_rotated,
)
from .profiles import get_profile, update_profile
from .services import list_services, get_service
from .orders import (
    create_order,
    get_order,
    get_user_order,
    set_order_checkout_reference,
    list_user_orders,
    get_latest_order_for_course,
)
from .payments import mark_order_paid, record_payment
from .feed import list_feed
from .activities import insert_activity
from .livekit_jobs import (
    create_webhook_job,
    delete_webhook_job,
    fetch_and_lock_due_webhook_jobs,
    get_webhook_job_counts,
    lock_webhook_job,
    mark_webhook_job_failed,
    release_processing_webhook_jobs,
    schedule_webhook_retry,
)
from .seminars import (
    get_seminar,
    list_host_seminars,
    list_public_seminars,
    create_seminar,
    update_seminar,
    set_seminar_status,
    create_seminar_session,
    update_seminar_session,
    get_session_by_room,
    get_seminar_session,
    get_latest_session,
    list_seminar_sessions,
    list_seminar_attendees,
    list_seminar_recordings,
    register_attendee,
    unregister_attendee,
    get_user_seminar_role,
    touch_attendee_presence,
    upsert_recording,
    user_can_access_seminar,
    user_has_seminar_access,
)
from .teacher_profile_media import (
    list_teacher_profile_media,
    get_teacher_profile_media,
    create_teacher_profile_media,
    update_teacher_profile_media,
    delete_teacher_profile_media,
    list_teacher_lesson_media_sources,
    list_teacher_seminar_recording_sources,
    list_public_teacher_profile_media,
)
from .home_player_library import (
    list_home_player_uploads,
    get_home_player_upload,
    create_home_player_upload,
    update_home_player_upload,
    delete_home_player_upload,
    list_home_player_course_links,
    get_home_player_course_link,
    resolve_lesson_media_course_owner,
    upsert_home_player_course_link,
    update_home_player_course_link,
    delete_home_player_course_link,
    get_active_home_upload_by_media_id,
)
from .subscriptions import get_latest_subscription, get_membership
from .memberships import upsert_membership_record
from .course_entitlements import grant_course_entitlement, list_entitlements_for_user
from .sessions import (
    create_session,
    update_session,
    get_session,
    delete_session,
    list_teacher_sessions,
    list_published_sessions,
    create_session_slot,
    update_session_slot,
    get_session_slot,
    list_session_slots,
)
from .media_assets import (
    create_media_asset,
    delete_media_asset,
    defer_media_asset_processing,
    fetch_and_lock_pending_media_assets,
    get_media_asset,
    get_media_asset_access,
    increment_processing_attempts,
    mark_media_asset_failed,
    mark_media_asset_ready,
    release_processing_media_assets,
)

__all__ = [
    # Auth
    "UniqueViolationError",
    "create_user",
    "get_user_by_email",
    "get_user_by_id",
    "upsert_refresh_token",
    "get_refresh_token",
    "insert_auth_event",
    "revoke_refresh_token",
    "touch_refresh_token_as_rotated",
    # Profiles
    "get_profile",
    "update_profile",
    # Services
    "list_services",
    "get_service",
    # Orders & payments
    "create_order",
    "get_order",
    "get_user_order",
    "set_order_checkout_reference",
    "list_user_orders",
    "get_latest_order_for_course",
    "mark_order_paid",
    "record_payment",
    # Feed
    "list_feed",
    # Activities
    "insert_activity",
    # LiveKit jobs
    "create_webhook_job",
    "delete_webhook_job",
    "fetch_and_lock_due_webhook_jobs",
    "get_webhook_job_counts",
    "lock_webhook_job",
    "mark_webhook_job_failed",
    "release_processing_webhook_jobs",
    "schedule_webhook_retry",
    # Seminars
    "get_seminar",
    "list_host_seminars",
    "list_public_seminars",
    "create_seminar",
    "update_seminar",
    "set_seminar_status",
    "create_seminar_session",
    "update_seminar_session",
    "get_session_by_room",
    "get_seminar_session",
    "get_latest_session",
    "list_seminar_sessions",
    "list_seminar_attendees",
    "list_seminar_recordings",
    "register_attendee",
    "unregister_attendee",
    "get_user_seminar_role",
    "touch_attendee_presence",
    "upsert_recording",
    "user_can_access_seminar",
    "user_has_seminar_access",
    # Teacher profile media
    "list_teacher_profile_media",
    "get_teacher_profile_media",
    "create_teacher_profile_media",
    "update_teacher_profile_media",
    "delete_teacher_profile_media",
    "list_teacher_lesson_media_sources",
    "list_teacher_seminar_recording_sources",
    "list_public_teacher_profile_media",
    # Home player library
    "list_home_player_uploads",
    "get_home_player_upload",
    "create_home_player_upload",
    "update_home_player_upload",
    "delete_home_player_upload",
    "list_home_player_course_links",
    "get_home_player_course_link",
    "resolve_lesson_media_course_owner",
    "upsert_home_player_course_link",
    "update_home_player_course_link",
    "delete_home_player_course_link",
    "get_active_home_upload_by_media_id",
    # Subscriptions
    "get_latest_subscription",
    "get_membership",
    "upsert_membership_record",
    "grant_course_entitlement",
    "list_entitlements_for_user",
    # Sessions/slots
    "create_session",
    "update_session",
    "get_session",
    "delete_session",
    "list_teacher_sessions",
    "list_published_sessions",
    "create_session_slot",
    "update_session_slot",
    "get_session_slot",
    "list_session_slots",
    # Media assets
    "create_media_asset",
    "delete_media_asset",
    "fetch_and_lock_pending_media_assets",
    "get_media_asset",
    "get_media_asset_access",
    "increment_processing_attempts",
    "mark_media_asset_failed",
    "mark_media_asset_ready",
    "defer_media_asset_processing",
    "release_processing_media_assets",
]
