"""Canonical package-level repository exports used by runtime code."""

from .activities import insert_activity
from .auth import (
    create_user,
    get_refresh_token,
    get_user_by_email,
    get_user_by_id,
    insert_auth_event,
    mark_user_email_verified,
    revoke_refresh_token,
    revoke_refresh_tokens_for_user,
    touch_refresh_token_as_rotated,
    upsert_refresh_token,
)
from .feed import list_feed
from .livekit_jobs import (
    create_webhook_job,
    delete_webhook_job,
    fetch_and_lock_due_webhook_jobs,
    get_webhook_job_counts,
    lock_webhook_job,
    mark_webhook_job_failed,
    release_processing_webhook_jobs,
    schedule_webhook_retry,
)
from .media_assets import get_media_asset
from .memberships import get_membership, upsert_membership_record
from .orders import (
    create_order,
    get_order,
    get_user_order,
    list_user_orders,
    set_order_checkout_reference,
)
from .payments import mark_order_paid
from .profiles import get_profile, set_onboarding_state, update_profile
from .seminars import (
    create_seminar,
    create_seminar_session,
    get_latest_session,
    get_seminar,
    get_seminar_session,
    get_session_by_room,
    get_user_seminar_role,
    list_host_seminars,
    list_public_seminars,
    list_seminar_attendees,
    list_seminar_recordings,
    list_seminar_sessions,
    register_attendee,
    set_seminar_status,
    touch_attendee_presence,
    unregister_attendee,
    update_seminar,
    update_seminar_session,
    upsert_recording,
    user_can_access_seminar,
    user_has_seminar_access,
)
from .services import get_service, list_services
from .sessions import (
    create_session,
    create_session_slot,
    delete_session,
    get_session,
    get_session_slot,
    list_published_sessions,
    list_session_slots,
    list_teacher_sessions,
    update_session,
    update_session_slot,
)
from .teacher_profile_media import (
    create_teacher_profile_media,
    delete_teacher_profile_media,
    get_teacher_profile_media,
    list_public_teacher_profile_media,
    list_teacher_lesson_media_sources,
    list_teacher_profile_media,
    list_teacher_seminar_recording_sources,
    update_teacher_profile_media,
)
from .teachers import get_teacher, update_teacher_status, upsert_teacher

__all__ = [
    "create_order",
    "create_seminar",
    "create_seminar_session",
    "create_session",
    "create_session_slot",
    "create_teacher_profile_media",
    "create_user",
    "create_webhook_job",
    "delete_session",
    "delete_teacher_profile_media",
    "delete_webhook_job",
    "fetch_and_lock_due_webhook_jobs",
    "get_latest_session",
    "get_media_asset",
    "get_membership",
    "get_order",
    "get_profile",
    "get_refresh_token",
    "get_seminar",
    "get_seminar_session",
    "get_service",
    "get_session",
    "get_session_by_room",
    "get_session_slot",
    "get_teacher",
    "get_teacher_profile_media",
    "get_user_by_email",
    "get_user_by_id",
    "get_user_order",
    "get_user_seminar_role",
    "get_webhook_job_counts",
    "insert_activity",
    "insert_auth_event",
    "list_feed",
    "list_host_seminars",
    "list_public_seminars",
    "list_public_teacher_profile_media",
    "list_published_sessions",
    "list_seminar_attendees",
    "list_seminar_recordings",
    "list_seminar_sessions",
    "list_services",
    "list_session_slots",
    "list_teacher_lesson_media_sources",
    "list_teacher_profile_media",
    "list_teacher_seminar_recording_sources",
    "list_teacher_sessions",
    "list_user_orders",
    "lock_webhook_job",
    "mark_order_paid",
    "mark_user_email_verified",
    "mark_webhook_job_failed",
    "register_attendee",
    "release_processing_webhook_jobs",
    "revoke_refresh_token",
    "revoke_refresh_tokens_for_user",
    "schedule_webhook_retry",
    "set_onboarding_state",
    "set_order_checkout_reference",
    "set_seminar_status",
    "touch_attendee_presence",
    "touch_refresh_token_as_rotated",
    "unregister_attendee",
    "update_profile",
    "update_seminar",
    "update_seminar_session",
    "update_session",
    "update_session_slot",
    "update_teacher_profile_media",
    "update_teacher_status",
    "upsert_membership_record",
    "upsert_recording",
    "upsert_refresh_token",
    "upsert_teacher",
    "user_can_access_seminar",
    "user_has_seminar_access",
]
