import uuid

import pytest

from app import db
from app.auth import create_access_token
from app.repositories import courses as courses_repo


pytestmark = pytest.mark.anyio("asyncio")


def _initialize_payload() -> dict:
    return {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
            "protocolVersion": "2025-11-25",
            "capabilities": {},
            "clientInfo": {"name": "pytest", "version": "0.1"},
        },
    }


def _auth_header(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


async def _register_teacher(async_client) -> tuple[dict[str, str], str]:
    email = f"logs_mcp_teacher_{uuid.uuid4().hex[:8]}@example.com"
    password = "Secret123!"
    user_id = str(uuid.uuid4())
    headers = _auth_header(create_access_token(user_id))

    async with db.pool.connection() as conn:  # type: ignore[attr-defined]
        async with conn.cursor() as cur:  # type: ignore[attr-defined]
            await cur.execute(
                """
                INSERT INTO auth.users (
                  id,
                  email,
                  encrypted_password,
                  created_at,
                  updated_at
                )
                VALUES (%s::uuid, %s, %s, now(), now())
                """,
                (user_id, email, "supabase-auth-managed-test-placeholder"),
            )
            await cur.execute(
                """
                INSERT INTO app.auth_subjects (
                  user_id,
                  email,
                  onboarding_state,
                  role
                )
                VALUES (%s::uuid, %s, 'completed', 'teacher')
                """,
                (user_id, email),
            )
            await cur.execute(
                """
                INSERT INTO app.memberships (
                  membership_id,
                  user_id,
                  status,
                  source,
                  created_at,
                  updated_at
                )
                VALUES (%s::uuid, %s::uuid, 'active', 'coupon', now(), now())
                """,
                (str(uuid.uuid4()), user_id),
            )
            await cur.execute(
                """
                INSERT INTO app.profiles (
                  user_id,
                  display_name,
                  bio,
                  avatar_media_id,
                  created_at,
                  updated_at
                )
                VALUES (%s::uuid, 'Teacher', null, null, now(), now())
                """,
                (user_id,),
            )
            await conn.commit()
    return headers, user_id


async def _create_course_and_lesson(async_client, headers: dict[str, str]) -> tuple[str, str]:
    slug = f"logs-mcp-course-{uuid.uuid4().hex[:6]}"
    course_resp = await async_client.post(
        "/studio/courses",
        headers=headers,
        json={
            "title": "Logs MCP Course",
            "slug": slug,
            "course_group_id": str(uuid.uuid4()),
            "group_position": 0,
            "price_amount_cents": None,
            "drip_enabled": False,
            "drip_interval_days": None,
        },
    )
    assert course_resp.status_code == 200, course_resp.text
    course_id = str(course_resp.json()["id"])

    lesson_resp = await async_client.post(
        f"/studio/courses/{course_id}/lessons",
        headers=headers,
        json={
            "lesson_title": "Logs Lesson",
            "position": 1,
        },
    )
    assert lesson_resp.status_code == 200, lesson_resp.text
    lesson_id = str(lesson_resp.json()["id"])
    return course_id, lesson_id


async def _ensure_media_resolution_failures_table() -> None:
    from app import db

    async with db.pool.connection() as conn:  # type: ignore[attr-defined]
        async with conn.cursor() as cur:  # type: ignore[attr-defined]
            await cur.execute(
                """
                CREATE TABLE IF NOT EXISTS app.media_resolution_failures (
                  id bigint generated by default as identity primary key,
                  created_at timestamptz not null default now(),
                  lesson_media_id uuid references app.lesson_media(id) on delete set null,
                  mode text not null,
                  reason text not null,
                  details jsonb not null default '{}'::jsonb
                )
                """
            )
            await cur.execute(
                """
                ALTER TABLE app.lesson_media
                  ADD COLUMN IF NOT EXISTS is_test boolean not null default false
                """
            )
            await cur.execute(
                """
                ALTER TABLE app.lesson_media
                  ADD COLUMN IF NOT EXISTS test_session_id uuid
                """
            )
            await cur.execute(
                """
                ALTER TABLE app.lessons
                  ADD COLUMN IF NOT EXISTS is_test boolean not null default false
                """
            )
            await cur.execute(
                """
                ALTER TABLE app.lessons
                  ADD COLUMN IF NOT EXISTS test_session_id uuid
                """
            )
            await cur.execute(
                """
                CREATE OR REPLACE FUNCTION app.is_test_row_visible(
                  row_is_test boolean,
                  row_test_session_id uuid
                )
                RETURNS boolean
                LANGUAGE sql
                STABLE
                AS $$
                  SELECT CASE
                    WHEN COALESCE(row_is_test, false) = false THEN true
                    WHEN NULLIF(current_setting('app.test_session_id', true), '') IS NULL
                      THEN false
                    ELSE row_test_session_id =
                      NULLIF(current_setting('app.test_session_id', true), '')::uuid
                  END
                $$
                """
            )
            await conn.commit()


async def _initialize_logs_mcp(async_client) -> None:
    response = await async_client.post(
        "/mcp/logs",
        json=_initialize_payload(),
        headers={"Accept": "application/json, text/event-stream"},
    )
    assert response.status_code == 200


async def test_logs_mcp_initialize_and_tool_call(async_client, monkeypatch):
    from app.routes import logs_mcp

    async def _fake_get_worker_health():
        return {
            "generated_at": "2026-03-23T12:00:00+00:00",
            "worker_health": {
                "media_transcode": {"status": "ok"},
                "livekit_webhooks": {"status": "stopped"},
                "membership_expiry_warnings": {"status": "ok"},
            },
            "safety": {"logs_mcp_enabled": True, "log_buffer_max_events": 500},
        }

    monkeypatch.setattr(
        logs_mcp.logs_observability,
        "get_worker_health",
        _fake_get_worker_health,
        raising=True,
    )
    monkeypatch.setattr(logs_mcp.settings, "mcp_mode", "local", raising=False)
    monkeypatch.setattr(logs_mcp.settings, "logs_mcp_enabled", True, raising=False)

    initialize = await async_client.post(
        "/mcp/logs",
        json=_initialize_payload(),
        headers={"Accept": "application/json, text/event-stream"},
    )
    assert initialize.status_code == 200
    init_payload = initialize.json()
    assert init_payload["result"]["protocolVersion"] == "2025-11-25"
    assert init_payload["result"]["serverInfo"]["name"] == "aveli-logs-mcp"

    tools_list = await async_client.post(
        "/mcp/logs",
        json={"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}},
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )
    assert tools_list.status_code == 200
    listed = tools_list.json()["result"]["tools"]
    assert {tool["name"] for tool in listed} == {
        "get_recent_errors",
        "get_media_failures",
        "get_cleanup_activity",
        "get_worker_health",
    }

    tool_call = await async_client.post(
        "/mcp/logs",
        json={
            "jsonrpc": "2.0",
            "id": 3,
            "method": "tools/call",
            "params": {"name": "get_worker_health", "arguments": {}},
        },
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )
    assert tool_call.status_code == 200
    result = tool_call.json()["result"]
    assert result["status"] == "ok"
    assert result["confidence"] == "high"
    assert result["source"]["server"] == "aveli-logs-mcp"
    assert result["data"]["worker_health"]["media_transcode"]["status"] == "ok"


async def test_logs_mcp_rejects_non_local_origin(async_client, monkeypatch):
    from app.routes import logs_mcp

    monkeypatch.setattr(logs_mcp.settings, "logs_mcp_enabled", True, raising=False)
    response = await async_client.post(
        "/mcp/logs",
        json=_initialize_payload(),
        headers={
            "Accept": "application/json, text/event-stream",
            "Origin": "https://evil.example",
        },
    )

    assert response.status_code == 403
    assert response.json()["detail"] == "Logs MCP rejected the supplied Origin header"


async def test_logs_mcp_invalid_window_returns_jsonrpc_error(async_client, monkeypatch):
    from app.routes import logs_mcp

    monkeypatch.setattr(logs_mcp.settings, "logs_mcp_enabled", True, raising=False)
    await async_client.post(
        "/mcp/logs",
        json=_initialize_payload(),
        headers={"Accept": "application/json, text/event-stream"},
    )

    response = await async_client.post(
        "/mcp/logs",
        json={
            "jsonrpc": "2.0",
            "id": 4,
            "method": "tools/call",
            "params": {
                "name": "get_cleanup_activity",
                "arguments": {"window": "90d"},
            },
        },
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )

    assert response.status_code == 200
    result = response.json()["result"]
    assert result["status"] == "error"
    assert result["confidence"] == "low"
    assert result["source"]["server"] == "aveli-logs-mcp"
    assert "Unsupported window" in result["data"]["error"]


async def test_logs_mcp_tools_execute_with_typed_media_failure_queries(async_client, monkeypatch):
    from app.repositories import media_assets as media_assets_repo
    from app.repositories import media_resolution_failures as media_resolution_failures_repo
    from app.routes import logs_mcp

    await _ensure_media_resolution_failures_table()
    monkeypatch.setattr(logs_mcp.settings, "mcp_mode", "local", raising=False)
    monkeypatch.setattr(logs_mcp.settings, "logs_mcp_enabled", True, raising=False)
    headers, user_id = await _register_teacher(async_client)
    course_id, lesson_id = await _create_course_and_lesson(async_client, headers)

    asset_id = str(uuid.uuid4())
    asset = await media_assets_repo.create_media_asset(
        media_asset_id=asset_id,
        media_type="audio",
        purpose="lesson_media",
        original_object_path=f"logs/{uuid.uuid4().hex}/source.mp3",
        ingest_format="mp3",
        state="pending_upload",
    )
    assert asset is not None
    await media_assets_repo.mark_media_asset_uploaded(media_id=asset_id)
    await media_assets_repo.mark_media_asset_failed(
        media_id=asset_id,
        error_message="logs mcp test failure",
    )

    lesson_media = await courses_repo.create_lesson_media(
        lesson_id=lesson_id,
        media_asset_id=asset_id,
    )
    assert lesson_media is not None

    await media_resolution_failures_repo.record_media_resolution_failure(
        lesson_media_id=str(lesson_media["lesson_media_id"]),
        mode="student_render",
        reason="missing_object",
        details={"source": "logs_mcp_test"},
    )

    await _initialize_logs_mcp(async_client)

    recent_errors = await async_client.post(
        "/mcp/logs",
        json={
            "jsonrpc": "2.0",
            "id": 5,
            "method": "tools/call",
            "params": {"name": "get_recent_errors", "arguments": {}},
        },
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )
    assert recent_errors.status_code == 200

    media_failures_unfiltered = await async_client.post(
        "/mcp/logs",
        json={
            "jsonrpc": "2.0",
            "id": 6,
            "method": "tools/call",
            "params": {
                "name": "get_media_failures",
                "arguments": {"asset_id": None},
            },
        },
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )
    assert media_failures_unfiltered.status_code == 200
    unfiltered_result = media_failures_unfiltered.json()["result"]
    assert unfiltered_result["status"] == "ok"
    assert unfiltered_result["confidence"] == "high"
    assert unfiltered_result["source"]["server"] == "aveli-logs-mcp"
    assert unfiltered_result["data"]["asset_id"] is None
    assert {
        item["source"]
        for item in unfiltered_result["data"]["media_failures"]
    } >= {"media_assets", "media_resolution_failures"}

    media_failures_filtered = await async_client.post(
        "/mcp/logs",
        json={
            "jsonrpc": "2.0",
            "id": 7,
            "method": "tools/call",
            "params": {
                "name": "get_media_failures",
                "arguments": {"asset_id": asset_id},
            },
        },
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )
    assert media_failures_filtered.status_code == 200
    filtered_result = media_failures_filtered.json()["result"]
    assert filtered_result["status"] == "ok"
    assert filtered_result["confidence"] == "high"
    assert filtered_result["source"]["server"] == "aveli-logs-mcp"
    assert filtered_result["data"]["asset_id"] == asset_id
    assert filtered_result["data"]["media_failures"]
    assert all(
        (item.get("details") or {}).get("asset_id") == asset_id
        for item in filtered_result["data"]["media_failures"]
        if item["source"] in {"media_assets", "media_resolution_failures"}
    )

    cleanup_activity = await async_client.post(
        "/mcp/logs",
        json={
            "jsonrpc": "2.0",
            "id": 8,
            "method": "tools/call",
            "params": {"name": "get_cleanup_activity", "arguments": {}},
        },
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )
    assert cleanup_activity.status_code == 200
    cleanup_result = cleanup_activity.json()["result"]
    assert cleanup_result["status"] == "ok"
    assert cleanup_result["confidence"] == "high"
    assert cleanup_result["source"]["server"] == "aveli-logs-mcp"


async def test_logs_mcp_notification_returns_accepted(async_client, monkeypatch):
    from app.routes import logs_mcp

    monkeypatch.setattr(logs_mcp.settings, "logs_mcp_enabled", True, raising=False)
    response = await async_client.post(
        "/mcp/logs",
        json={"jsonrpc": "2.0", "method": "notifications/initialized"},
        headers={
            "Accept": "application/json, text/event-stream",
            "MCP-Protocol-Version": "2025-11-25",
        },
    )

    assert response.status_code == 202
