from __future__ import annotations

from typing import Any

_API_SURFACE = "/studio/home-player/library"
_SOURCE_CONTRACT = "actual_truth/contracts/backend_text_catalog_contract.md"


def _entry(
    *,
    surface_id: str,
    text_id: str,
    authority_class: str,
    backend_namespace: str,
    render_surface: str,
    value: str,
) -> dict[str, Any]:
    return {
        "surface_id": surface_id,
        "text_id": text_id,
        "authority_class": authority_class,
        "canonical_owner": "backend_text_catalog",
        "source_contract": _SOURCE_CONTRACT,
        "backend_namespace": backend_namespace,
        "api_surface": _API_SURFACE,
        "delivery_surface": _API_SURFACE,
        "render_surface": render_surface,
        "language": "sv",
        "interpolation_keys": [],
        "forbidden_render_fields": [],
        "value": value,
    }


def build_studio_home_player_text_bundle() -> dict[str, dict[str, Any]]:
    profile_page = "frontend/lib/features/studio/presentation/profile_media_page.dart"
    upload_dialog = "frontend/lib/features/studio/widgets/home_player_upload_dialog.dart"
    upload_routing = "frontend/lib/features/studio/widgets/home_player_upload_routing.dart"
    studio_ns = "backend_text_catalog.studio_editor"
    home_ns = "backend_text_catalog.home"

    entries = [
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_library_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Home-spelarens bibliotek",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_uploads_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ljud för Home-spelaren",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_uploads_description",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value=(
                "Ladda upp ljud direkt för Home-spelaren. Dessa filer är "
                "fristående från kurser. Tar du bort en fil här raderas den helt."
            ),
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_uploads_empty_title",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Inga uppladdningar ännu.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_uploads_empty_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ladda upp ljud som bara ska användas i Home-spelaren.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_links_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Länkat ljud från kurser",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_links_description",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value=(
                "Här ser du ljud som är länkat från kursmaterial. Du kan slå på "
                "eller av länken, eller ta bort den utan att påverka originalfilen.\n"
                "Inga uppladdningar görs här."
            ),
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_links_empty_title",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Inga länkar ännu.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_links_empty_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value=(
                "Länka in ljud från dina kurser. Tar du bort originalfilen blir "
                "länken ogiltig och kan inte spelas."
            ),
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.home_player_link_action",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Länka ljud",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.refresh_action",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Uppdatera",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.retry_action",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Försök igen",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.upload_delete_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ta bort uppladdad fil",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.upload_delete_message",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Filen raderas helt och går inte att ångra.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.upload_delete_action",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ta bort",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.link_delete_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ta bort länk",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.link_delete_message",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Originalfilen i kursen påverkas inte.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.link_delete_action",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ta bort länk",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.cancel_action",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Avbryt",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.audio_kind_label",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ljudfil",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.processing_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Bearbetar ljud…",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.processing_failed_error",
            authority_class="backend_error_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Bearbetningen misslyckades.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.title_required_error",
            authority_class="backend_error_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Filnamn kan inte vara tomt.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.upload_prompt_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Namn på ljudfil",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.upload_prompt_hint",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value='T.ex. "Andningsövning"',
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.upload_ready_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Uppladdning klar.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.link_prompt_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Namn på länkat ljud",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.link_prompt_hint",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value='T.ex. "Meditation kväll"',
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.no_course_audio_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Inga kursljud hittades.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.link_created_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Ljudet har länkats.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.course_picker_title",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Välj kursljud att länka",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.course_picker_search_hint",
            authority_class="contract_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Sök på kurs eller lektion...",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.course_picker_empty_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Inga ljudfiler matchar sökningen.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.course_link_active_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Aktiv",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.course_link_source_missing_error",
            authority_class="backend_error_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Källa saknas",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.course_link_unpublished_status",
            authority_class="backend_status_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Kurs ej publicerad",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.action_failed_error",
            authority_class="backend_error_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Åtgärden kunde inte genomföras. Försök igen.",
        ),
        _entry(
            surface_id="TXT-SURF-071",
            text_id="studio_editor.profile_media.load_failed_error",
            authority_class="backend_error_text",
            backend_namespace=studio_ns,
            render_surface=profile_page,
            value="Biblioteket kunde inte läsas in. Försök igen.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.title",
            authority_class="contract_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Lägg till ljud i hemspelaren",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.audio_label",
            authority_class="contract_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Ljudfil",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.submit_action",
            authority_class="contract_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Ladda upp",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.uploading_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Laddar upp ljud...",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.processing_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Ljudet bearbetas...",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.ready_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Ljudet är redo.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.failed_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Ljudet kunde inte laddas upp.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.prepare_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Förbereder uppladdning...",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.registering_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Registrerar ljudfil...",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.processing_failed_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Bearbetningen misslyckades.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.refresh_failed_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Kunde inte uppdatera statusen just nu.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.wait_until_complete_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Vänta tills uppladdningen är klar eller avbryt.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.close_action",
            authority_class="contract_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Stäng",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.cancel_action",
            authority_class="contract_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Avbryt",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.retry_action",
            authority_class="contract_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Försök igen",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.cancelled_status",
            authority_class="backend_status_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Uppladdningen avbröts.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.audio_only_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Home-spelaren stöder bara ljudfiler.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.start_failed_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Kunde inte starta uppladdningen. Försök igen.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.save_failed_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_dialog,
            value="Kunde inte spara uppladdningen. Försök igen.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.unsupported_audio_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_routing,
            value="Endast WAV eller MP3 stöds för ljud i Home-spelaren.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.unsupported_video_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_routing,
            value="Home-spelaren stöder bara ljud. Välj en WAV- eller MP3-fil.",
        ),
        _entry(
            surface_id="TXT-SURF-075",
            text_id="home.player_upload.unsupported_other_error",
            authority_class="backend_error_text",
            backend_namespace=home_ns,
            render_surface=upload_routing,
            value="Välj en WAV- eller MP3-fil.",
        ),
    ]
    return {entry["text_id"]: entry for entry in entries}
