create table if not exists app.media_resolution_failures (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lesson_media_id uuid references app.lesson_media(id) on delete set null,
  mode text not null check (mode in ('editor_insert', 'editor_preview', 'student_render')),
  reason text not null check (
    reason in (
      'missing_object',
      'bucket_mismatch',
      'key_format_drift',
      'cannot_sign',
      'unsupported'
    )
  ),
  details jsonb not null default '{}'::jsonb
);

create index if not exists idx_media_resolution_failures_created_at
  on app.media_resolution_failures(created_at desc);

create index if not exists idx_media_resolution_failures_lesson_media
  on app.media_resolution_failures(lesson_media_id);

create index if not exists idx_media_resolution_failures_reason
  on app.media_resolution_failures(reason);

create table if not exists app.lesson_media_issues (
  lesson_media_id uuid primary key references app.lesson_media(id) on delete cascade,
  issue text not null check (
    issue in (
      'missing_object',
      'bucket_mismatch',
      'key_format_drift',
      'unsupported'
    )
  ),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_lesson_media_issues_issue
  on app.lesson_media_issues(issue);

